# version: '3'
# services:
#   db:
#     image: mysql:5.6
#     env_file:
#       - ./environments/db:env
#     ports:
#       - "80:80"
#     volumes:
#       - mysql_data:/var/lib/mysql # データの永続化
#   web:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     command: bundle exec rails s -p 3000 -b '0.0.0.0'
#     tty: true
#     stdin_open: true
#     depends_on:
#       - db # DB側のコンテナが出来上がってからwebを実行する
#     ports:
#       - "3000:3000" # ホストからゲストへポートフォワード
#     volumes:
#       - .:/myapp # ソースコード変更したらDocker側も即反映されるように
# volumes:
#   mysql_data: # データの永続化

version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: